// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"universal/app/gateway/internal/biz"
	"universal/app/gateway/internal/conf"
	"universal/app/gateway/internal/data"
	"universal/app/gateway/internal/server"
	"universal/app/gateway/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	discovery := data.NewDiscovery(registry)
	userClient := data.NewUserServiceClient(discovery)
	aiClient := data.NewAiServiceClient(discovery)
	conversationClient := data.NewConversationServiceClient(discovery)
	modelClient := data.NewModelServiceClient(discovery)
	knowledgeClient := data.NewKnowledgeServiceClient(discovery)
	toolClient := data.NewToolServiceClient(discovery)
	dataData, cleanup, err := data.NewData(confData, logger, userClient, aiClient, conversationClient, modelClient, knowledgeClient, toolClient)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	gatewayRepo := data.NewGatewayRepo(dataData, logger)
	gatewayUsecase := biz.NewGatewayUsecase(gatewayRepo, logger)
	gatewayService := service.NewGatewayService(gatewayUsecase, logger)
	userRepo := data.NewUserRepo(dataData, logger)
	userUsecase := biz.NewUserUsecase(userRepo, logger)
	userService := service.NewUserService(userUsecase)
	aiService := service.NewAiService(dataData, userUsecase, logger)
	conversationService := service.NewConversationService(dataData, userUsecase, logger)
	knowledgeService := service.NewKnowledgeService()
	toolService := service.NewToolService()
	grpcServer := server.NewGRPCServer(confServer, greeterService, gatewayService, userService, aiService, conversationService, knowledgeService, toolService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, gatewayService, userService, aiService, conversationService, knowledgeService, toolService, logger)
	registrar := data.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
