// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/gateway/v1/ai.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	v1 "universal/api/ai/v1"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_gateway_v1_ai_proto protoreflect.FileDescriptor

const file_api_gateway_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x17api/gateway/v1/ai.proto\x12\x10api.universal.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x12api/ai/v1/ai.proto2\x87\a\n" +
	"\x02Ai\x12\x9f\x01\n" +
	"\x18GetConversationAnalytics\x12*.api.ai.v1.GetConversationAnalyticsRequest\x1a(.api.ai.v1.GetConversationAnalyticsReply\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/ai/v1/analytics/conversations\x12\x88\x01\n" +
	"\x11GetUserUsageStats\x12#.api.ai.v1.GetUserUsageStatsRequest\x1a!.api.ai.v1.GetUserUsageStatsReply\"+\x82\xd3\xe4\x93\x02%:\x01*\" /api/ai/v1/analytics/usage/users\x12\xa4\x01\n" +
	"\x18GetModelPerformanceStats\x12*.api.ai.v1.GetModelPerformanceStatsRequest\x1a(.api.ai.v1.GetModelPerformanceStatsReply\"2\x82\xd3\xe4\x93\x02,:\x01*\"'/api/ai/v1/analytics/models/performance\x12\x9d\x01\n" +
	"\x15GetConversationTrends\x12'.api.ai.v1.GetConversationTrendsRequest\x1a%.api.ai.v1.GetConversationTrendsReply\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/ai/v1/analytics/conversations/trends\x12\x80\x01\n" +
	"\x10GetTopicAnalysis\x12\".api.ai.v1.GetTopicAnalysisRequest\x1a .api.ai.v1.GetTopicAnalysisReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/ai/v1/analytics/topics\x12\x89\x01\n" +
	"\x11GetSystemOverview\x12#.api.ai.v1.GetSystemOverviewRequest\x1a!.api.ai.v1.GetSystemOverviewReply\",\x82\xd3\xe4\x93\x02&\x12$/api/ai/v1/analytics/system/overviewBO\n" +
	"#com.oldwei.universal.api.gateway.v1B\tAiProtoV1P\x01Z\x1buniversal/api/gateway/v1;v1b\x06proto3"

var file_api_gateway_v1_ai_proto_goTypes = []any{
	(*v1.GetConversationAnalyticsRequest)(nil), // 0: api.ai.v1.GetConversationAnalyticsRequest
	(*v1.GetUserUsageStatsRequest)(nil),        // 1: api.ai.v1.GetUserUsageStatsRequest
	(*v1.GetModelPerformanceStatsRequest)(nil), // 2: api.ai.v1.GetModelPerformanceStatsRequest
	(*v1.GetConversationTrendsRequest)(nil),    // 3: api.ai.v1.GetConversationTrendsRequest
	(*v1.GetTopicAnalysisRequest)(nil),         // 4: api.ai.v1.GetTopicAnalysisRequest
	(*v1.GetSystemOverviewRequest)(nil),        // 5: api.ai.v1.GetSystemOverviewRequest
	(*v1.GetConversationAnalyticsReply)(nil),   // 6: api.ai.v1.GetConversationAnalyticsReply
	(*v1.GetUserUsageStatsReply)(nil),          // 7: api.ai.v1.GetUserUsageStatsReply
	(*v1.GetModelPerformanceStatsReply)(nil),   // 8: api.ai.v1.GetModelPerformanceStatsReply
	(*v1.GetConversationTrendsReply)(nil),      // 9: api.ai.v1.GetConversationTrendsReply
	(*v1.GetTopicAnalysisReply)(nil),           // 10: api.ai.v1.GetTopicAnalysisReply
	(*v1.GetSystemOverviewReply)(nil),          // 11: api.ai.v1.GetSystemOverviewReply
}
var file_api_gateway_v1_ai_proto_depIdxs = []int32{
	0,  // 0: api.universal.v1.Ai.GetConversationAnalytics:input_type -> api.ai.v1.GetConversationAnalyticsRequest
	1,  // 1: api.universal.v1.Ai.GetUserUsageStats:input_type -> api.ai.v1.GetUserUsageStatsRequest
	2,  // 2: api.universal.v1.Ai.GetModelPerformanceStats:input_type -> api.ai.v1.GetModelPerformanceStatsRequest
	3,  // 3: api.universal.v1.Ai.GetConversationTrends:input_type -> api.ai.v1.GetConversationTrendsRequest
	4,  // 4: api.universal.v1.Ai.GetTopicAnalysis:input_type -> api.ai.v1.GetTopicAnalysisRequest
	5,  // 5: api.universal.v1.Ai.GetSystemOverview:input_type -> api.ai.v1.GetSystemOverviewRequest
	6,  // 6: api.universal.v1.Ai.GetConversationAnalytics:output_type -> api.ai.v1.GetConversationAnalyticsReply
	7,  // 7: api.universal.v1.Ai.GetUserUsageStats:output_type -> api.ai.v1.GetUserUsageStatsReply
	8,  // 8: api.universal.v1.Ai.GetModelPerformanceStats:output_type -> api.ai.v1.GetModelPerformanceStatsReply
	9,  // 9: api.universal.v1.Ai.GetConversationTrends:output_type -> api.ai.v1.GetConversationTrendsReply
	10, // 10: api.universal.v1.Ai.GetTopicAnalysis:output_type -> api.ai.v1.GetTopicAnalysisReply
	11, // 11: api.universal.v1.Ai.GetSystemOverview:output_type -> api.ai.v1.GetSystemOverviewReply
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_ai_proto_init() }
func file_api_gateway_v1_ai_proto_init() {
	if File_api_gateway_v1_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_ai_proto_rawDesc), len(file_api_gateway_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_ai_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_ai_proto_depIdxs,
	}.Build()
	File_api_gateway_v1_ai_proto = out.File
	file_api_gateway_v1_ai_proto_goTypes = nil
	file_api_gateway_v1_ai_proto_depIdxs = nil
}
