// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: api/gateway/v1/ai.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	v1 "universal/api/ai/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Ai_GetConversationAnalytics_FullMethodName = "/api.universal.v1.Ai/GetConversationAnalytics"
	Ai_GetUserUsageStats_FullMethodName        = "/api.universal.v1.Ai/GetUserUsageStats"
	Ai_GetModelPerformanceStats_FullMethodName = "/api.universal.v1.Ai/GetModelPerformanceStats"
	Ai_GetConversationTrends_FullMethodName    = "/api.universal.v1.Ai/GetConversationTrends"
	Ai_GetTopicAnalysis_FullMethodName         = "/api.universal.v1.Ai/GetTopicAnalysis"
	Ai_GetSystemOverview_FullMethodName        = "/api.universal.v1.Ai/GetSystemOverview"
)

// AiClient is the client API for Ai service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Gateway AI服务接口 - 提供HTTP访问AI服务的统一入口
type AiClient interface {
	// GetConversationAnalytics 获取对话统计分析数据
	GetConversationAnalytics(ctx context.Context, in *v1.GetConversationAnalyticsRequest, opts ...grpc.CallOption) (*v1.GetConversationAnalyticsReply, error)
	// GetUserUsageStats 获取用户使用统计
	GetUserUsageStats(ctx context.Context, in *v1.GetUserUsageStatsRequest, opts ...grpc.CallOption) (*v1.GetUserUsageStatsReply, error)
	// GetModelPerformanceStats 获取模型性能统计
	GetModelPerformanceStats(ctx context.Context, in *v1.GetModelPerformanceStatsRequest, opts ...grpc.CallOption) (*v1.GetModelPerformanceStatsReply, error)
	// GetConversationTrends 获取对话趋势分析
	GetConversationTrends(ctx context.Context, in *v1.GetConversationTrendsRequest, opts ...grpc.CallOption) (*v1.GetConversationTrendsReply, error)
	// GetTopicAnalysis 获取话题分析
	GetTopicAnalysis(ctx context.Context, in *v1.GetTopicAnalysisRequest, opts ...grpc.CallOption) (*v1.GetTopicAnalysisReply, error)
	// GetSystemOverview 获取系统总览统计
	GetSystemOverview(ctx context.Context, in *v1.GetSystemOverviewRequest, opts ...grpc.CallOption) (*v1.GetSystemOverviewReply, error)
}

type aiClient struct {
	cc grpc.ClientConnInterface
}

func NewAiClient(cc grpc.ClientConnInterface) AiClient {
	return &aiClient{cc}
}

func (c *aiClient) GetConversationAnalytics(ctx context.Context, in *v1.GetConversationAnalyticsRequest, opts ...grpc.CallOption) (*v1.GetConversationAnalyticsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetConversationAnalyticsReply)
	err := c.cc.Invoke(ctx, Ai_GetConversationAnalytics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) GetUserUsageStats(ctx context.Context, in *v1.GetUserUsageStatsRequest, opts ...grpc.CallOption) (*v1.GetUserUsageStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetUserUsageStatsReply)
	err := c.cc.Invoke(ctx, Ai_GetUserUsageStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) GetModelPerformanceStats(ctx context.Context, in *v1.GetModelPerformanceStatsRequest, opts ...grpc.CallOption) (*v1.GetModelPerformanceStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetModelPerformanceStatsReply)
	err := c.cc.Invoke(ctx, Ai_GetModelPerformanceStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) GetConversationTrends(ctx context.Context, in *v1.GetConversationTrendsRequest, opts ...grpc.CallOption) (*v1.GetConversationTrendsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetConversationTrendsReply)
	err := c.cc.Invoke(ctx, Ai_GetConversationTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) GetTopicAnalysis(ctx context.Context, in *v1.GetTopicAnalysisRequest, opts ...grpc.CallOption) (*v1.GetTopicAnalysisReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetTopicAnalysisReply)
	err := c.cc.Invoke(ctx, Ai_GetTopicAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aiClient) GetSystemOverview(ctx context.Context, in *v1.GetSystemOverviewRequest, opts ...grpc.CallOption) (*v1.GetSystemOverviewReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.GetSystemOverviewReply)
	err := c.cc.Invoke(ctx, Ai_GetSystemOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AiServer is the server API for Ai service.
// All implementations must embed UnimplementedAiServer
// for forward compatibility.
//
// Gateway AI服务接口 - 提供HTTP访问AI服务的统一入口
type AiServer interface {
	// GetConversationAnalytics 获取对话统计分析数据
	GetConversationAnalytics(context.Context, *v1.GetConversationAnalyticsRequest) (*v1.GetConversationAnalyticsReply, error)
	// GetUserUsageStats 获取用户使用统计
	GetUserUsageStats(context.Context, *v1.GetUserUsageStatsRequest) (*v1.GetUserUsageStatsReply, error)
	// GetModelPerformanceStats 获取模型性能统计
	GetModelPerformanceStats(context.Context, *v1.GetModelPerformanceStatsRequest) (*v1.GetModelPerformanceStatsReply, error)
	// GetConversationTrends 获取对话趋势分析
	GetConversationTrends(context.Context, *v1.GetConversationTrendsRequest) (*v1.GetConversationTrendsReply, error)
	// GetTopicAnalysis 获取话题分析
	GetTopicAnalysis(context.Context, *v1.GetTopicAnalysisRequest) (*v1.GetTopicAnalysisReply, error)
	// GetSystemOverview 获取系统总览统计
	GetSystemOverview(context.Context, *v1.GetSystemOverviewRequest) (*v1.GetSystemOverviewReply, error)
	mustEmbedUnimplementedAiServer()
}

// UnimplementedAiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAiServer struct{}

func (UnimplementedAiServer) GetConversationAnalytics(context.Context, *v1.GetConversationAnalyticsRequest) (*v1.GetConversationAnalyticsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationAnalytics not implemented")
}
func (UnimplementedAiServer) GetUserUsageStats(context.Context, *v1.GetUserUsageStatsRequest) (*v1.GetUserUsageStatsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserUsageStats not implemented")
}
func (UnimplementedAiServer) GetModelPerformanceStats(context.Context, *v1.GetModelPerformanceStatsRequest) (*v1.GetModelPerformanceStatsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetModelPerformanceStats not implemented")
}
func (UnimplementedAiServer) GetConversationTrends(context.Context, *v1.GetConversationTrendsRequest) (*v1.GetConversationTrendsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConversationTrends not implemented")
}
func (UnimplementedAiServer) GetTopicAnalysis(context.Context, *v1.GetTopicAnalysisRequest) (*v1.GetTopicAnalysisReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTopicAnalysis not implemented")
}
func (UnimplementedAiServer) GetSystemOverview(context.Context, *v1.GetSystemOverviewRequest) (*v1.GetSystemOverviewReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemOverview not implemented")
}
func (UnimplementedAiServer) mustEmbedUnimplementedAiServer() {}
func (UnimplementedAiServer) testEmbeddedByValue()            {}

// UnsafeAiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AiServer will
// result in compilation errors.
type UnsafeAiServer interface {
	mustEmbedUnimplementedAiServer()
}

func RegisterAiServer(s grpc.ServiceRegistrar, srv AiServer) {
	// If the following call pancis, it indicates UnimplementedAiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Ai_ServiceDesc, srv)
}

func _Ai_GetConversationAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetConversationAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).GetConversationAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_GetConversationAnalytics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).GetConversationAnalytics(ctx, req.(*v1.GetConversationAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_GetUserUsageStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetUserUsageStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).GetUserUsageStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_GetUserUsageStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).GetUserUsageStats(ctx, req.(*v1.GetUserUsageStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_GetModelPerformanceStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetModelPerformanceStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).GetModelPerformanceStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_GetModelPerformanceStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).GetModelPerformanceStats(ctx, req.(*v1.GetModelPerformanceStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_GetConversationTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetConversationTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).GetConversationTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_GetConversationTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).GetConversationTrends(ctx, req.(*v1.GetConversationTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_GetTopicAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetTopicAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).GetTopicAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_GetTopicAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).GetTopicAnalysis(ctx, req.(*v1.GetTopicAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ai_GetSystemOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.GetSystemOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AiServer).GetSystemOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Ai_GetSystemOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AiServer).GetSystemOverview(ctx, req.(*v1.GetSystemOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ai_ServiceDesc is the grpc.ServiceDesc for Ai service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ai_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.universal.v1.Ai",
	HandlerType: (*AiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConversationAnalytics",
			Handler:    _Ai_GetConversationAnalytics_Handler,
		},
		{
			MethodName: "GetUserUsageStats",
			Handler:    _Ai_GetUserUsageStats_Handler,
		},
		{
			MethodName: "GetModelPerformanceStats",
			Handler:    _Ai_GetModelPerformanceStats_Handler,
		},
		{
			MethodName: "GetConversationTrends",
			Handler:    _Ai_GetConversationTrends_Handler,
		},
		{
			MethodName: "GetTopicAnalysis",
			Handler:    _Ai_GetTopicAnalysis_Handler,
		},
		{
			MethodName: "GetSystemOverview",
			Handler:    _Ai_GetSystemOverview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/gateway/v1/ai.proto",
}
