// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/gateway/v1/tool.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	v1 "universal/api/ai/v1"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_gateway_v1_tool_proto protoreflect.FileDescriptor

const file_api_gateway_v1_tool_proto_rawDesc = "" +
	"\n" +
	"\x19api/gateway/v1/tool.proto\x12\x10api.universal.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x14api/ai/v1/tool.proto2\xdc\x16\n" +
	"\x04Tool\x12]\n" +
	"\tListTools\x12\x1b.api.ai.v1.ListToolsRequest\x1a\x19.api.ai.v1.ListToolsReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/api/ai/v1/tools\x12^\n" +
	"\aGetTool\x12\x19.api.ai.v1.GetToolRequest\x1a\x17.api.ai.v1.GetToolReply\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/ai/v1/tools/{name}\x12e\n" +
	"\bCallTool\x12\x1a.api.ai.v1.CallToolRequest\x1a\x1b.api.ai.v1.CallToolResponse\" \x82\xd3\xe4\x93\x02\x1a:\x01*\"\x15/api/ai/v1/tools/call\x12z\n" +
	"\x0eCallToolStream\x12\x1a.api.ai.v1.CallToolRequest\x1a!.api.ai.v1.CallToolStreamResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/ai/v1/tools/call/stream0\x01\x12w\n" +
	"\rGetToolSchema\x12\x1f.api.ai.v1.GetToolSchemaRequest\x1a\x1d.api.ai.v1.GetToolSchemaReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/ai/v1/tools/{name}/schema\x12\x8d\x01\n" +
	"\x15ValidateToolArguments\x12'.api.ai.v1.ValidateToolArgumentsRequest\x1a%.api.ai.v1.ValidateToolArgumentsReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\"\x19/api/ai/v1/tools/validate\x12z\n" +
	"\x0eBatchCallTools\x12 .api.ai.v1.BatchCallToolsRequest\x1a\x1e.api.ai.v1.BatchCallToolsReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/ai/v1/tools/batch-call\x12x\n" +
	"\x0eListMcpServers\x12 .api.ai.v1.ListMcpServersRequest\x1a\x1e.api.ai.v1.ListMcpServersReply\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/ai/v1/tools/mcp/servers\x12w\n" +
	"\fGetMcpServer\x12\x1e.api.ai.v1.GetMcpServerRequest\x1a\x1c.api.ai.v1.GetMcpServerReply\")\x82\xd3\xe4\x93\x02#\x12!/api/ai/v1/tools/mcp/servers/{id}\x12\x84\x01\n" +
	"\x11RegisterMcpServer\x12#.api.ai.v1.RegisterMcpServerRequest\x1a!.api.ai.v1.RegisterMcpServerReply\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/api/ai/v1/tools/mcp/servers\x12\x83\x01\n" +
	"\x0fUpdateMcpServer\x12!.api.ai.v1.UpdateMcpServerRequest\x1a\x1f.api.ai.v1.UpdateMcpServerReply\",\x82\xd3\xe4\x93\x02&:\x01*\x1a!/api/ai/v1/tools/mcp/servers/{id}\x12\x80\x01\n" +
	"\x0fDeleteMcpServer\x12!.api.ai.v1.DeleteMcpServerRequest\x1a\x1f.api.ai.v1.DeleteMcpServerReply\")\x82\xd3\xe4\x93\x02#*!/api/ai/v1/tools/mcp/servers/{id}\x12\x82\x01\n" +
	"\rTestMcpServer\x12\x1f.api.ai.v1.TestMcpServerRequest\x1a\x1d.api.ai.v1.TestMcpServerReply\"1\x82\xd3\xe4\x93\x02+:\x01*\"&/api/ai/v1/tools/mcp/servers/{id}/test\x12w\n" +
	"\rListResources\x12\x1f.api.ai.v1.ListResourcesRequest\x1a\x1d.api.ai.v1.ListResourcesReply\"&\x82\xd3\xe4\x93\x02 \x12\x1e/api/ai/v1/tools/mcp/resources\x12w\n" +
	"\vGetResource\x12\x1d.api.ai.v1.GetResourceRequest\x1a\x1b.api.ai.v1.GetResourceReply\",\x82\xd3\xe4\x93\x02&\x12$/api/ai/v1/tools/mcp/resources/{uri}\x12\x87\x01\n" +
	"\x0fSearchResources\x12!.api.ai.v1.SearchResourcesRequest\x1a\x1f.api.ai.v1.SearchResourcesReply\"0\x82\xd3\xe4\x93\x02*:\x01*\"%/api/ai/v1/tools/mcp/resources/search\x12\x85\x01\n" +
	"\rWatchResource\x12\x1f.api.ai.v1.WatchResourceRequest\x1a\x1d.api.ai.v1.WatchResourceReply\"2\x82\xd3\xe4\x93\x02,\x12*/api/ai/v1/tools/mcp/resources/{uri}/watch0\x01\x12\x99\x01\n" +
	"\x17GetToolExecutionHistory\x12).api.ai.v1.GetToolExecutionHistoryRequest\x1a'.api.ai.v1.GetToolExecutionHistoryReply\"*\x82\xd3\xe4\x93\x02$\x12\"/api/ai/v1/tools/execution/history\x12\x91\x01\n" +
	"\x15GetToolExecutionStats\x12'.api.ai.v1.GetToolExecutionStatsRequest\x1a%.api.ai.v1.GetToolExecutionStatsReply\"(\x82\xd3\xe4\x93\x02\"\x12 /api/ai/v1/tools/execution/stats\x12v\n" +
	"\n" +
	"EnableTool\x12\x1c.api.ai.v1.EnableToolRequest\x1a\x1a.api.ai.v1.EnableToolReply\".\x82\xd3\xe4\x93\x02(:\x01*\"#/api/ai/v1/tools/{tool_name}/enable\x12z\n" +
	"\vDisableTool\x12\x1d.api.ai.v1.DisableToolRequest\x1a\x1b.api.ai.v1.DisableToolReply\"/\x82\xd3\xe4\x93\x02):\x01*\"$/api/ai/v1/tools/{tool_name}/disable\x12\x7f\n" +
	"\rConfigureTool\x12\x1f.api.ai.v1.ConfigureToolRequest\x1a\x1d.api.ai.v1.ConfigureToolReply\".\x82\xd3\xe4\x93\x02(:\x01*\x1a#/api/ai/v1/tools/{tool_name}/config\x12|\n" +
	"\rGetToolConfig\x12\x1f.api.ai.v1.GetToolConfigRequest\x1a\x1d.api.ai.v1.GetToolConfigReply\"+\x82\xd3\xe4\x93\x02%\x12#/api/ai/v1/tools/{tool_name}/configBQ\n" +
	"#com.oldwei.universal.api.gateway.v1B\vToolProtoV1P\x01Z\x1buniversal/api/gateway/v1;v1b\x06proto3"

var file_api_gateway_v1_tool_proto_goTypes = []any{
	(*v1.ListToolsRequest)(nil),               // 0: api.ai.v1.ListToolsRequest
	(*v1.GetToolRequest)(nil),                 // 1: api.ai.v1.GetToolRequest
	(*v1.CallToolRequest)(nil),                // 2: api.ai.v1.CallToolRequest
	(*v1.GetToolSchemaRequest)(nil),           // 3: api.ai.v1.GetToolSchemaRequest
	(*v1.ValidateToolArgumentsRequest)(nil),   // 4: api.ai.v1.ValidateToolArgumentsRequest
	(*v1.BatchCallToolsRequest)(nil),          // 5: api.ai.v1.BatchCallToolsRequest
	(*v1.ListMcpServersRequest)(nil),          // 6: api.ai.v1.ListMcpServersRequest
	(*v1.GetMcpServerRequest)(nil),            // 7: api.ai.v1.GetMcpServerRequest
	(*v1.RegisterMcpServerRequest)(nil),       // 8: api.ai.v1.RegisterMcpServerRequest
	(*v1.UpdateMcpServerRequest)(nil),         // 9: api.ai.v1.UpdateMcpServerRequest
	(*v1.DeleteMcpServerRequest)(nil),         // 10: api.ai.v1.DeleteMcpServerRequest
	(*v1.TestMcpServerRequest)(nil),           // 11: api.ai.v1.TestMcpServerRequest
	(*v1.ListResourcesRequest)(nil),           // 12: api.ai.v1.ListResourcesRequest
	(*v1.GetResourceRequest)(nil),             // 13: api.ai.v1.GetResourceRequest
	(*v1.SearchResourcesRequest)(nil),         // 14: api.ai.v1.SearchResourcesRequest
	(*v1.WatchResourceRequest)(nil),           // 15: api.ai.v1.WatchResourceRequest
	(*v1.GetToolExecutionHistoryRequest)(nil), // 16: api.ai.v1.GetToolExecutionHistoryRequest
	(*v1.GetToolExecutionStatsRequest)(nil),   // 17: api.ai.v1.GetToolExecutionStatsRequest
	(*v1.EnableToolRequest)(nil),              // 18: api.ai.v1.EnableToolRequest
	(*v1.DisableToolRequest)(nil),             // 19: api.ai.v1.DisableToolRequest
	(*v1.ConfigureToolRequest)(nil),           // 20: api.ai.v1.ConfigureToolRequest
	(*v1.GetToolConfigRequest)(nil),           // 21: api.ai.v1.GetToolConfigRequest
	(*v1.ListToolsReply)(nil),                 // 22: api.ai.v1.ListToolsReply
	(*v1.GetToolReply)(nil),                   // 23: api.ai.v1.GetToolReply
	(*v1.CallToolResponse)(nil),               // 24: api.ai.v1.CallToolResponse
	(*v1.CallToolStreamResponse)(nil),         // 25: api.ai.v1.CallToolStreamResponse
	(*v1.GetToolSchemaReply)(nil),             // 26: api.ai.v1.GetToolSchemaReply
	(*v1.ValidateToolArgumentsReply)(nil),     // 27: api.ai.v1.ValidateToolArgumentsReply
	(*v1.BatchCallToolsReply)(nil),            // 28: api.ai.v1.BatchCallToolsReply
	(*v1.ListMcpServersReply)(nil),            // 29: api.ai.v1.ListMcpServersReply
	(*v1.GetMcpServerReply)(nil),              // 30: api.ai.v1.GetMcpServerReply
	(*v1.RegisterMcpServerReply)(nil),         // 31: api.ai.v1.RegisterMcpServerReply
	(*v1.UpdateMcpServerReply)(nil),           // 32: api.ai.v1.UpdateMcpServerReply
	(*v1.DeleteMcpServerReply)(nil),           // 33: api.ai.v1.DeleteMcpServerReply
	(*v1.TestMcpServerReply)(nil),             // 34: api.ai.v1.TestMcpServerReply
	(*v1.ListResourcesReply)(nil),             // 35: api.ai.v1.ListResourcesReply
	(*v1.GetResourceReply)(nil),               // 36: api.ai.v1.GetResourceReply
	(*v1.SearchResourcesReply)(nil),           // 37: api.ai.v1.SearchResourcesReply
	(*v1.WatchResourceReply)(nil),             // 38: api.ai.v1.WatchResourceReply
	(*v1.GetToolExecutionHistoryReply)(nil),   // 39: api.ai.v1.GetToolExecutionHistoryReply
	(*v1.GetToolExecutionStatsReply)(nil),     // 40: api.ai.v1.GetToolExecutionStatsReply
	(*v1.EnableToolReply)(nil),                // 41: api.ai.v1.EnableToolReply
	(*v1.DisableToolReply)(nil),               // 42: api.ai.v1.DisableToolReply
	(*v1.ConfigureToolReply)(nil),             // 43: api.ai.v1.ConfigureToolReply
	(*v1.GetToolConfigReply)(nil),             // 44: api.ai.v1.GetToolConfigReply
}
var file_api_gateway_v1_tool_proto_depIdxs = []int32{
	0,  // 0: api.universal.v1.Tool.ListTools:input_type -> api.ai.v1.ListToolsRequest
	1,  // 1: api.universal.v1.Tool.GetTool:input_type -> api.ai.v1.GetToolRequest
	2,  // 2: api.universal.v1.Tool.CallTool:input_type -> api.ai.v1.CallToolRequest
	2,  // 3: api.universal.v1.Tool.CallToolStream:input_type -> api.ai.v1.CallToolRequest
	3,  // 4: api.universal.v1.Tool.GetToolSchema:input_type -> api.ai.v1.GetToolSchemaRequest
	4,  // 5: api.universal.v1.Tool.ValidateToolArguments:input_type -> api.ai.v1.ValidateToolArgumentsRequest
	5,  // 6: api.universal.v1.Tool.BatchCallTools:input_type -> api.ai.v1.BatchCallToolsRequest
	6,  // 7: api.universal.v1.Tool.ListMcpServers:input_type -> api.ai.v1.ListMcpServersRequest
	7,  // 8: api.universal.v1.Tool.GetMcpServer:input_type -> api.ai.v1.GetMcpServerRequest
	8,  // 9: api.universal.v1.Tool.RegisterMcpServer:input_type -> api.ai.v1.RegisterMcpServerRequest
	9,  // 10: api.universal.v1.Tool.UpdateMcpServer:input_type -> api.ai.v1.UpdateMcpServerRequest
	10, // 11: api.universal.v1.Tool.DeleteMcpServer:input_type -> api.ai.v1.DeleteMcpServerRequest
	11, // 12: api.universal.v1.Tool.TestMcpServer:input_type -> api.ai.v1.TestMcpServerRequest
	12, // 13: api.universal.v1.Tool.ListResources:input_type -> api.ai.v1.ListResourcesRequest
	13, // 14: api.universal.v1.Tool.GetResource:input_type -> api.ai.v1.GetResourceRequest
	14, // 15: api.universal.v1.Tool.SearchResources:input_type -> api.ai.v1.SearchResourcesRequest
	15, // 16: api.universal.v1.Tool.WatchResource:input_type -> api.ai.v1.WatchResourceRequest
	16, // 17: api.universal.v1.Tool.GetToolExecutionHistory:input_type -> api.ai.v1.GetToolExecutionHistoryRequest
	17, // 18: api.universal.v1.Tool.GetToolExecutionStats:input_type -> api.ai.v1.GetToolExecutionStatsRequest
	18, // 19: api.universal.v1.Tool.EnableTool:input_type -> api.ai.v1.EnableToolRequest
	19, // 20: api.universal.v1.Tool.DisableTool:input_type -> api.ai.v1.DisableToolRequest
	20, // 21: api.universal.v1.Tool.ConfigureTool:input_type -> api.ai.v1.ConfigureToolRequest
	21, // 22: api.universal.v1.Tool.GetToolConfig:input_type -> api.ai.v1.GetToolConfigRequest
	22, // 23: api.universal.v1.Tool.ListTools:output_type -> api.ai.v1.ListToolsReply
	23, // 24: api.universal.v1.Tool.GetTool:output_type -> api.ai.v1.GetToolReply
	24, // 25: api.universal.v1.Tool.CallTool:output_type -> api.ai.v1.CallToolResponse
	25, // 26: api.universal.v1.Tool.CallToolStream:output_type -> api.ai.v1.CallToolStreamResponse
	26, // 27: api.universal.v1.Tool.GetToolSchema:output_type -> api.ai.v1.GetToolSchemaReply
	27, // 28: api.universal.v1.Tool.ValidateToolArguments:output_type -> api.ai.v1.ValidateToolArgumentsReply
	28, // 29: api.universal.v1.Tool.BatchCallTools:output_type -> api.ai.v1.BatchCallToolsReply
	29, // 30: api.universal.v1.Tool.ListMcpServers:output_type -> api.ai.v1.ListMcpServersReply
	30, // 31: api.universal.v1.Tool.GetMcpServer:output_type -> api.ai.v1.GetMcpServerReply
	31, // 32: api.universal.v1.Tool.RegisterMcpServer:output_type -> api.ai.v1.RegisterMcpServerReply
	32, // 33: api.universal.v1.Tool.UpdateMcpServer:output_type -> api.ai.v1.UpdateMcpServerReply
	33, // 34: api.universal.v1.Tool.DeleteMcpServer:output_type -> api.ai.v1.DeleteMcpServerReply
	34, // 35: api.universal.v1.Tool.TestMcpServer:output_type -> api.ai.v1.TestMcpServerReply
	35, // 36: api.universal.v1.Tool.ListResources:output_type -> api.ai.v1.ListResourcesReply
	36, // 37: api.universal.v1.Tool.GetResource:output_type -> api.ai.v1.GetResourceReply
	37, // 38: api.universal.v1.Tool.SearchResources:output_type -> api.ai.v1.SearchResourcesReply
	38, // 39: api.universal.v1.Tool.WatchResource:output_type -> api.ai.v1.WatchResourceReply
	39, // 40: api.universal.v1.Tool.GetToolExecutionHistory:output_type -> api.ai.v1.GetToolExecutionHistoryReply
	40, // 41: api.universal.v1.Tool.GetToolExecutionStats:output_type -> api.ai.v1.GetToolExecutionStatsReply
	41, // 42: api.universal.v1.Tool.EnableTool:output_type -> api.ai.v1.EnableToolReply
	42, // 43: api.universal.v1.Tool.DisableTool:output_type -> api.ai.v1.DisableToolReply
	43, // 44: api.universal.v1.Tool.ConfigureTool:output_type -> api.ai.v1.ConfigureToolReply
	44, // 45: api.universal.v1.Tool.GetToolConfig:output_type -> api.ai.v1.GetToolConfigReply
	23, // [23:46] is the sub-list for method output_type
	0,  // [0:23] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_gateway_v1_tool_proto_init() }
func file_api_gateway_v1_tool_proto_init() {
	if File_api_gateway_v1_tool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gateway_v1_tool_proto_rawDesc), len(file_api_gateway_v1_tool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gateway_v1_tool_proto_goTypes,
		DependencyIndexes: file_api_gateway_v1_tool_proto_depIdxs,
	}.Build()
	File_api_gateway_v1_tool_proto = out.File
	file_api_gateway_v1_tool_proto_goTypes = nil
	file_api_gateway_v1_tool_proto_depIdxs = nil
}
