// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"universal/app/ai/internal/biz"
	"universal/app/ai/internal/conf"
	"universal/app/ai/internal/data"
	"universal/app/ai/internal/server"
	"universal/app/ai/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, registry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	aiRepo := data.NewAiRepo(dataData, logger)
	aiUsecase := biz.NewAiUsecase(aiRepo, logger)
	aiService := service.NewAiService(aiUsecase)
	providerRepo := data.NewProviderRepo(dataData, logger)
	modelRepo := data.NewModelRepo(dataData, logger)
	quotaRepo := data.NewQuotaRepo(dataData, logger)
	rateLimitRepo := data.NewRateLimitRepo(dataData, logger)
	healthRepo := data.NewHealthRepo(dataData, logger)
	modelUsecase := biz.NewModelUsecase(providerRepo, modelRepo, quotaRepo, rateLimitRepo, healthRepo, logger)
	modelService := service.NewModelService(modelUsecase)
	grpcServer := server.NewGRPCServer(confServer, aiService, modelService, logger)
	httpServer := server.NewHTTPServer(confServer, aiService, logger)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, httpServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
