// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: api/universal/v1/universal.proto

package v1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email    string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	// 密码字段已移除，不在响应中返回
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"` // 1:正常 0:禁用
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UserInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateUserRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateUserRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type CreateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReply) Reset() {
	*x = CreateUserReply{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReply) ProtoMessage() {}

func (x *CreateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReply.ProtoReflect.Descriptor instead.
func (*CreateUserReply) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserReply) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Nickname      string                 `protobuf:"bytes,5,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        int32                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateUserRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReply) Reset() {
	*x = UpdateUserReply{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReply) ProtoMessage() {}

func (x *UpdateUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReply.ProtoReflect.Descriptor instead.
func (*UpdateUserReply) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserReply) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReply) Reset() {
	*x = GetUserReply{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReply) ProtoMessage() {}

func (x *GetUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReply.ProtoReflect.Descriptor instead.
func (*GetUserReply) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserReply) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type ListUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserRequest) Reset() {
	*x = ListUserRequest{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserRequest) ProtoMessage() {}

func (x *ListUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserRequest.ProtoReflect.Descriptor instead.
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{8}
}

func (x *ListUserRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListUserRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *ListUserRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*UserInfo            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserReply) Reset() {
	*x = ListUserReply{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserReply) ProtoMessage() {}

func (x *ListUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserReply.ProtoReflect.Descriptor instead.
func (*ListUserReply) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{9}
}

func (x *ListUserReply) GetUsers() []*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUserReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListUserReply) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserReply) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 通用操作响应
type OperationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`                                  // 操作是否成功
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                   // 操作结果消息
	AffectedCount int32                  `protobuf:"varint,3,opt,name=affected_count,json=affectedCount,proto3" json:"affected_count,omitempty"` // 影响的记录数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationReply) Reset() {
	*x = OperationReply{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationReply) ProtoMessage() {}

func (x *OperationReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationReply.ProtoReflect.Descriptor instead.
func (*OperationReply) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{10}
}

func (x *OperationReply) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OperationReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationReply) GetAffectedCount() int32 {
	if x != nil {
		return x.AffectedCount
	}
	return 0
}

// 扩展操作消息定义
type BatchDeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteUserRequest) Reset() {
	*x = BatchDeleteUserRequest{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteUserRequest) ProtoMessage() {}

func (x *BatchDeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteUserRequest.ProtoReflect.Descriptor instead.
func (*BatchDeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{11}
}

func (x *BatchDeleteUserRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type BatchDeleteUserReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeletedCount  int32                  `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"` // 成功删除数量
	FailedCount   int32                  `protobuf:"varint,2,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`    // 删除失败数量
	FailedIds     []int64                `protobuf:"varint,3,rep,packed,name=failed_ids,json=failedIds,proto3" json:"failed_ids,omitempty"`   // 删除失败的ID列表
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                                // 操作结果消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteUserReply) Reset() {
	*x = BatchDeleteUserReply{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteUserReply) ProtoMessage() {}

func (x *BatchDeleteUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteUserReply.ProtoReflect.Descriptor instead.
func (*BatchDeleteUserReply) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{12}
}

func (x *BatchDeleteUserReply) GetDeletedCount() int32 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

func (x *BatchDeleteUserReply) GetFailedCount() int32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *BatchDeleteUserReply) GetFailedIds() []int64 {
	if x != nil {
		return x.FailedIds
	}
	return nil
}

func (x *BatchDeleteUserReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusRequest) Reset() {
	*x = UpdateUserStatusRequest{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusRequest) ProtoMessage() {}

func (x *UpdateUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateUserStatusRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserStatusRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{14}
}

func (x *ChangePasswordRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type GetUserStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{15}
}

type GetUserStatsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers    int64                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`            // 总用户数
	ActiveUsers   int64                  `protobuf:"varint,2,opt,name=active_users,json=activeUsers,proto3" json:"active_users,omitempty"`         // 活跃用户数
	DisabledUsers int64                  `protobuf:"varint,3,opt,name=disabled_users,json=disabledUsers,proto3" json:"disabled_users,omitempty"`   // 禁用用户数
	TodayNewUsers int64                  `protobuf:"varint,4,opt,name=today_new_users,json=todayNewUsers,proto3" json:"today_new_users,omitempty"` // 今日新增用户数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatsReply) Reset() {
	*x = GetUserStatsReply{}
	mi := &file_api_universal_v1_universal_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsReply) ProtoMessage() {}

func (x *GetUserStatsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_universal_v1_universal_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsReply.ProtoReflect.Descriptor instead.
func (*GetUserStatsReply) Descriptor() ([]byte, []int) {
	return file_api_universal_v1_universal_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserStatsReply) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetUserStatsReply) GetActiveUsers() int64 {
	if x != nil {
		return x.ActiveUsers
	}
	return 0
}

func (x *GetUserStatsReply) GetDisabledUsers() int64 {
	if x != nil {
		return x.DisabledUsers
	}
	return 0
}

func (x *GetUserStatsReply) GetTodayNewUsers() int64 {
	if x != nil {
		return x.TodayNewUsers
	}
	return 0
}

var File_api_universal_v1_universal_proto protoreflect.FileDescriptor

const file_api_universal_v1_universal_proto_rawDesc = "" +
	"\n" +
	" api/universal/v1/universal.proto\x12\x10api.universal.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17validate/validate.proto\"\xa4\x02\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x1a\n" +
	"\bnickname\x18\x05 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe9\x01\n" +
	"\x11CreateUserRequest\x12%\n" +
	"\busername\x18\x01 \x01(\tB\t\xfaB\x06r\x04\x10\x03\x182R\busername\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x06R\bpassword\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12#\n" +
	"\bnickname\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x18dR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"A\n" +
	"\x0fCreateUserReply\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x1a.api.universal.v1.UserInfoR\x04user\"\xd2\x01\n" +
	"\x11UpdateUserRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12\x1d\n" +
	"\x05email\x18\x02 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12#\n" +
	"\bnickname\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x18dR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x06 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06status\x18\a \x01(\x05R\x06status\"A\n" +
	"\x0fUpdateUserReply\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x1a.api.universal.v1.UserInfoR\x04user\",\n" +
	"\x11DeleteUserRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\">\n" +
	"\fGetUserReply\x12.\n" +
	"\x04user\x18\x01 \x01(\v2\x1a.api.universal.v1.UserInfoR\x04user\"\x88\x01\n" +
	"\x0fListUserRequest\x12\x1b\n" +
	"\x04page\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x04page\x12&\n" +
	"\tpage_size\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x04\x18d(\x01R\bpageSize\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\x88\x01\n" +
	"\rListUserReply\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.api.universal.v1.UserInfoR\x05users\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"k\n" +
	"\x0eOperationReply\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0eaffected_count\x18\x03 \x01(\x05R\raffectedCount\"4\n" +
	"\x16BatchDeleteUserRequest\x12\x1a\n" +
	"\x03ids\x18\x01 \x03(\x03B\b\xfaB\x05\x92\x01\x02\b\x01R\x03ids\"\x97\x01\n" +
	"\x14BatchDeleteUserReply\x12#\n" +
	"\rdeleted_count\x18\x01 \x01(\x05R\fdeletedCount\x12!\n" +
	"\ffailed_count\x18\x02 \x01(\x05R\vfailedCount\x12\x1d\n" +
	"\n" +
	"failed_ids\x18\x03 \x03(\x03R\tfailedIds\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"U\n" +
	"\x17UpdateUserStatusRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12!\n" +
	"\x06status\x18\x02 \x01(\x05B\t\xfaB\x06\x1a\x040\x000\x01R\x06status\"\x88\x01\n" +
	"\x15ChangePasswordRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x03B\a\xfaB\x04\"\x02 \x00R\x02id\x12*\n" +
	"\fold_password\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x06R\voldPassword\x12*\n" +
	"\fnew_password\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x06R\vnewPassword\"\x15\n" +
	"\x13GetUserStatsRequest\"\xa6\x01\n" +
	"\x11GetUserStatsReply\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12!\n" +
	"\factive_users\x18\x02 \x01(\x03R\vactiveUsers\x12%\n" +
	"\x0edisabled_users\x18\x03 \x01(\x03R\rdisabledUsers\x12&\n" +
	"\x0ftoday_new_users\x18\x04 \x01(\x03R\rtodayNewUsers2\x84\t\n" +
	"\tUniversal\x12u\n" +
	"\n" +
	"CreateUser\x12#.api.universal.v1.CreateUserRequest\x1a!.api.universal.v1.CreateUserReply\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/api/system/v1/users\x12z\n" +
	"\n" +
	"UpdateUser\x12#.api.universal.v1.UpdateUserRequest\x1a!.api.universal.v1.UpdateUserReply\"$\x82\xd3\xe4\x93\x02\x1e:\x01*\x1a\x19/api/system/v1/users/{id}\x12v\n" +
	"\n" +
	"DeleteUser\x12#.api.universal.v1.DeleteUserRequest\x1a .api.universal.v1.OperationReply\"!\x82\xd3\xe4\x93\x02\x1b*\x19/api/system/v1/users/{id}\x12n\n" +
	"\aGetUser\x12 .api.universal.v1.GetUserRequest\x1a\x1e.api.universal.v1.GetUserReply\"!\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/system/v1/users/{id}\x12l\n" +
	"\bListUser\x12!.api.universal.v1.ListUserRequest\x1a\x1f.api.universal.v1.ListUserReply\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/api/system/v1/users\x12\x91\x01\n" +
	"\x0fBatchDeleteUser\x12(.api.universal.v1.BatchDeleteUserRequest\x1a&.api.universal.v1.BatchDeleteUserReply\",\x82\xd3\xe4\x93\x02&:\x01*\"!/api/system/v1/users/batch-delete\x12\x8c\x01\n" +
	"\x10UpdateUserStatus\x12).api.universal.v1.UpdateUserStatusRequest\x1a .api.universal.v1.OperationReply\"+\x82\xd3\xe4\x93\x02%:\x01*2 /api/system/v1/users/{id}/status\x12\x8a\x01\n" +
	"\x0eChangePassword\x12'.api.universal.v1.ChangePasswordRequest\x1a .api.universal.v1.OperationReply\"-\x82\xd3\xe4\x93\x02':\x01*2\"/api/system/v1/users/{id}/password\x12~\n" +
	"\fGetUserStats\x12%.api.universal.v1.GetUserStatsRequest\x1a#.api.universal.v1.GetUserStatsReply\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/system/v1/users/statsBZ\n" +
	"%com.oldwei.universal.api.universal.v1B\x10UniversalProtoV1P\x01Z\x1duniversal/api/universal/v1;v1b\x06proto3"

var (
	file_api_universal_v1_universal_proto_rawDescOnce sync.Once
	file_api_universal_v1_universal_proto_rawDescData []byte
)

func file_api_universal_v1_universal_proto_rawDescGZIP() []byte {
	file_api_universal_v1_universal_proto_rawDescOnce.Do(func() {
		file_api_universal_v1_universal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_universal_v1_universal_proto_rawDesc), len(file_api_universal_v1_universal_proto_rawDesc)))
	})
	return file_api_universal_v1_universal_proto_rawDescData
}

var file_api_universal_v1_universal_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_universal_v1_universal_proto_goTypes = []any{
	(*UserInfo)(nil),                // 0: api.universal.v1.UserInfo
	(*CreateUserRequest)(nil),       // 1: api.universal.v1.CreateUserRequest
	(*CreateUserReply)(nil),         // 2: api.universal.v1.CreateUserReply
	(*UpdateUserRequest)(nil),       // 3: api.universal.v1.UpdateUserRequest
	(*UpdateUserReply)(nil),         // 4: api.universal.v1.UpdateUserReply
	(*DeleteUserRequest)(nil),       // 5: api.universal.v1.DeleteUserRequest
	(*GetUserRequest)(nil),          // 6: api.universal.v1.GetUserRequest
	(*GetUserReply)(nil),            // 7: api.universal.v1.GetUserReply
	(*ListUserRequest)(nil),         // 8: api.universal.v1.ListUserRequest
	(*ListUserReply)(nil),           // 9: api.universal.v1.ListUserReply
	(*OperationReply)(nil),          // 10: api.universal.v1.OperationReply
	(*BatchDeleteUserRequest)(nil),  // 11: api.universal.v1.BatchDeleteUserRequest
	(*BatchDeleteUserReply)(nil),    // 12: api.universal.v1.BatchDeleteUserReply
	(*UpdateUserStatusRequest)(nil), // 13: api.universal.v1.UpdateUserStatusRequest
	(*ChangePasswordRequest)(nil),   // 14: api.universal.v1.ChangePasswordRequest
	(*GetUserStatsRequest)(nil),     // 15: api.universal.v1.GetUserStatsRequest
	(*GetUserStatsReply)(nil),       // 16: api.universal.v1.GetUserStatsReply
	(*timestamppb.Timestamp)(nil),   // 17: google.protobuf.Timestamp
}
var file_api_universal_v1_universal_proto_depIdxs = []int32{
	17, // 0: api.universal.v1.UserInfo.created_at:type_name -> google.protobuf.Timestamp
	17, // 1: api.universal.v1.UserInfo.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: api.universal.v1.CreateUserReply.user:type_name -> api.universal.v1.UserInfo
	0,  // 3: api.universal.v1.UpdateUserReply.user:type_name -> api.universal.v1.UserInfo
	0,  // 4: api.universal.v1.GetUserReply.user:type_name -> api.universal.v1.UserInfo
	0,  // 5: api.universal.v1.ListUserReply.users:type_name -> api.universal.v1.UserInfo
	1,  // 6: api.universal.v1.Universal.CreateUser:input_type -> api.universal.v1.CreateUserRequest
	3,  // 7: api.universal.v1.Universal.UpdateUser:input_type -> api.universal.v1.UpdateUserRequest
	5,  // 8: api.universal.v1.Universal.DeleteUser:input_type -> api.universal.v1.DeleteUserRequest
	6,  // 9: api.universal.v1.Universal.GetUser:input_type -> api.universal.v1.GetUserRequest
	8,  // 10: api.universal.v1.Universal.ListUser:input_type -> api.universal.v1.ListUserRequest
	11, // 11: api.universal.v1.Universal.BatchDeleteUser:input_type -> api.universal.v1.BatchDeleteUserRequest
	13, // 12: api.universal.v1.Universal.UpdateUserStatus:input_type -> api.universal.v1.UpdateUserStatusRequest
	14, // 13: api.universal.v1.Universal.ChangePassword:input_type -> api.universal.v1.ChangePasswordRequest
	15, // 14: api.universal.v1.Universal.GetUserStats:input_type -> api.universal.v1.GetUserStatsRequest
	2,  // 15: api.universal.v1.Universal.CreateUser:output_type -> api.universal.v1.CreateUserReply
	4,  // 16: api.universal.v1.Universal.UpdateUser:output_type -> api.universal.v1.UpdateUserReply
	10, // 17: api.universal.v1.Universal.DeleteUser:output_type -> api.universal.v1.OperationReply
	7,  // 18: api.universal.v1.Universal.GetUser:output_type -> api.universal.v1.GetUserReply
	9,  // 19: api.universal.v1.Universal.ListUser:output_type -> api.universal.v1.ListUserReply
	12, // 20: api.universal.v1.Universal.BatchDeleteUser:output_type -> api.universal.v1.BatchDeleteUserReply
	10, // 21: api.universal.v1.Universal.UpdateUserStatus:output_type -> api.universal.v1.OperationReply
	10, // 22: api.universal.v1.Universal.ChangePassword:output_type -> api.universal.v1.OperationReply
	16, // 23: api.universal.v1.Universal.GetUserStats:output_type -> api.universal.v1.GetUserStatsReply
	15, // [15:24] is the sub-list for method output_type
	6,  // [6:15] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_universal_v1_universal_proto_init() }
func file_api_universal_v1_universal_proto_init() {
	if File_api_universal_v1_universal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_universal_v1_universal_proto_rawDesc), len(file_api_universal_v1_universal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_universal_v1_universal_proto_goTypes,
		DependencyIndexes: file_api_universal_v1_universal_proto_depIdxs,
		MessageInfos:      file_api_universal_v1_universal_proto_msgTypes,
	}.Build()
	File_api_universal_v1_universal_proto = out.File
	file_api_universal_v1_universal_proto_goTypes = nil
	file_api_universal_v1_universal_proto_depIdxs = nil
}
